<div class="jm-masshead" <?php if(isset($config['background'])): ?> style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$config['background']; ?>)" <?php endif; ?>>
	<div class="main">
		<div class="inner">
			<h3 class="jm-masshead-title"><?php echo $config['title']; ?></h3>
			<div class="jm-masshead-desc"><?php echo $config['description']; ?></div>
		</div>
	</div>
</div>