<?php
/*!
 * http://www.ubertheme.com/
 * Version: 1.0
 * Description:
 * Author: Uber theme team
 * Author URI: http://www.ubertheme.com/
 *
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
?>

<?php
	$thumbWidth = $config['width'];
	$thumbHeight = $config['height'];
	$maxChar = $config['max'];

	// Image loading
	$loadingImage = $this->getSkinUrl('joomlart/jmproducts/images/loader.gif');

	// Calculator with
	if ($config['perrow']){
		$perrow = $config['perrow'];
		$width = 100/$config['perrow'];
	}

	$baseconfig =  Mage::helper("jmbasetheme")->getactiveprofile();
  if ($baseconfig) : 
    $showLabel = $baseconfig["showlabel"];
  else :
    $showLabel = 0;
  endif;
	// Tablet
	$perrowtablet = $config["perrowtablet"];
	$widthtablet = 100/$config["perrowtablet"];
	if (isset($config["perrowtabletportrait"])){
		$perrowtabletportrait = $config["perrowtabletportrait"];
		$widthtabletportrait = 100/$config["perrowtabletportrait"];
	}
	else {
		$perrowtabletportrait = $perrowtablet;
		$widthtabletportrait = $widthtablet;
	}

	// Mobile
	$perrowmobile = $config["perrowmobile"];
	$widthmobile = 100/$config["perrowmobile"];
	if (isset($config["perrowmobileportrait"])){
		$perrowmobileportrait = $config["perrowmobileportrait"];
		$widthmobiletportrait = 100/$config["perrowmobileportrait"];
	}
	else {
		$perrowmobileportrait = $perrowmobile;
		$widthmobiletportrait = $widthmobile;
	}
?>
<style type="text/css">
	.jm-product-list ul.products-grid li.item {
			width: <?php echo $width.'%';?>;
		}
	.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
    clear: both;
	}
	@media only screen and (min-width:986px) and (max-width: 1235px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthtablet.'%';?>;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
	    clear: both;
		}
	}
	@media only screen and (min-width:720px) and (max-width: 985px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthtabletportrait.'%';?>;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtabletportrait;?>n+1) {
	    clear: both;
		}
	}
	@media only screen and (max-width:719px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthmobile.'%';?>;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtabletportrait;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowmobile;?>n+1) {
	    clear: both;
		}
	}
	@media only screen and (max-width:479px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthmobiletportrait.'%';?>;
		}
		<?php if ($perrowmobileportrait == 1):?>
			.jm-product-list ul.products-grid {
				margin: 0;
			}
		<?php endif; ?>
	}
</style>

<?php $listId = uniqid(); ?>

<script type="text/javascript">
	(function($){
		$(document).ready(function () {
			$("#productsgrid_<?php echo $listId; ?>").jmproduct({
				configs:<?php echo json_encode($config); ?>,
				qtytable:<?php echo $config['qtytable']; ?>,
				qtytableportrait:<?php echo $config['qtytableportrait']; ?>,
				istable:<?php echo $config['istable']; ?>,
				qtymobile:<?php echo $config['qtymobile']; ?>,
				qtymobileportrait:<?php echo $config['qtymobileportrait']; ?>,
				ismobile:<?php echo $config['ismobile']; ?>,
				finished_message: "<?php echo $this->__("That's all we have for now.") ?>"
			});
		});
	})(jQuery);
</script>

<!-- List products -->
<div class="jm-product-list <?php echo $config['mode']; ?> clearfix">
	<?php /*
	if($config['title']):
		Mage::getSingleton('core/session')->setData('jm_product_title', $config['title']);
	?>
		<div class="page-title category-title clearfix">
			<h2><?php echo Mage::getSingleton('core/session')->getData('jm_product_title'); ?></h2>
		</div>
	<?php endif; */ ?>

	<div class="listing-type-grid category-products">
		<?php
		$collection = $this->getCollection();
		$collectionSize = $collection ? $collection->count() : 0;
		$i = 0;
		?>

		<?php if ($collectionSize): ?>
			<ul id="productsgrid_<?php echo $listId; ?>" class="products-grid" >
				<?php
				$j = 0;
				foreach ($collection->getItems() as $product):
					$rowCount = ceil($collectionSize / $config['perrow']);
					if ($i % $config['perrow'] == 0){
						$j++;
					}
					$i++;

					$product = Mage::getModel('catalog/product')->load($product->getId());
					$attribute = $product->getResource()->getAttribute('label');
					if (is_object($attribute)) {
						$options = $attribute->getSource()->getAllOptions(true, true);
						foreach ($options as $option) {
							if ($option['value'] == $product->getData("label")) {
								$class = $option['label'];
							}
						}
						$attDefaultValue = $attribute->getDefaultValue();
						$attributeValue = Mage::getModel('catalog/product')->load($product->getId())->getlabel();
						$attributeValueName = Mage::getModel('catalog/product')->load($product->getId())->getAttributeText('label');
						if (strlen($attributeValue) && ($attDefaultValue !== $attributeValue)) {
							$labelType = $class;
							$labelName = $attributeValueName;
						} else {
							$labelType = "";
						}
					}
					?>
					<li class="item <?php if ($j == $rowCount) : echo "item-row-last"; endif; ?> <?php if (($i - 1) % $config['perrow'] == 0): ?> first<?php elseif ($i % $config['perrow'] == 0): ?> last<?php endif; ?> p-item">
						<div class="inner">
							<!-- Product image -->
							<div class="product-image">
								<a title="<?php echo $this->htmlEscape($product->getName()) ?>" class="image-link"
								   href="<?php echo $product->getProductUrl() ?>">
									<img
										src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize($thumbWidth, $thumbHeight)->setWatermarkSize('30x10'); ?>"
										alt="<?php echo $this->htmlEscape($product->getName()) ?>"/>
								</a>
								<?php if (isset($labelType) && isset($labelName) && $showLabel): ?>
									<span class="ico-label <?php echo $labelType; ?>-label"><?php echo $labelName; ?></span>
								<?php endif; ?>
								<div class="actions">
								<?php // echo $this->getReviewsSummaryHtml($product, true, true) ?>
								<!-- Add to cart -->
								<?php if ($product->isSaleable()): ?>
									<button class="button btn-cart"
											onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')">
										<span><?php echo $this->helper("catalog")->__('Add to Cart'); ?></span>
									</button>
								<?php else: ?>
									<div class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock'); ?></div>
								<?php endif; ?>
								<!-- Add to links -->
								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li>
											<a href="<?php echo $this->helper('wishlist')->getAddUrl($product); ?>" class="link-wishlist">
												<?php echo $this->__('Wishlist'); ?>
											</a>
										</li>
									<?php endif; ?>
									<?php if ($compareUrl = $this->getAddToCompareUrl($product)): ?>
										<li>
											<a href="<?php echo $compareUrl ?>" class="link-compare"><?php echo $this->__('Compare'); ?></a>
										</li>
									<?php endif; ?>
								</ul>
							</div>
							</div>
							<a  class="product-name" title="<?php echo $this->htmlEscape($product->getName()) ?>" href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a>
							<?php echo $this->getPriceHtml($product, true, '_jmproduct_' . uniqid()); ?>
							<?php
									if ($maxChar) :
										$productDesc = $product->getDescription();
										$productShortDesc = $product->getShortDescription();
								?>
									<p class="pdescription"><?php echo substr(nl2br(strlen($productDesc) > 10 ? $productDesc : $productShortDesc), 0, $maxChar) . '...'; ?></p>
								<?php endif; ?>
						</div>
					</li>
				<?php endforeach; ?>
			</ul>
			<!--ajax load more button -->
			<?php
				$totalPage = $this->getTotalPage();
				if($config['page'] < $totalPage):
			?>
			<div id="productsgrid_<?php echo $listId; ?>-item-more" class="item-more">
				<div class="inner item-inner clearfix">
					<h3>
						<a onclick="javascript:void(0);" data-total-page="<?php echo $totalPage; ?>" data-next-page="<?php echo ($config['page']+1); ?>" data-href="<?php echo Mage::getModel('core/url')->getUrl('jmproducts/index/ajaxLoadMore', array());?>" >
							<?php echo $this->__('Load more...'); ?>
						</a>
					</h3>
				</div>
			</div>
			<?php endif;?>
			<!--//ajax load more button -->

			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>

		<?php else: ?>
			<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php endif; ?>
	</div>
</div>
<div class="clearfix"></div>
<!--// List products -->