<?php
/*!
 * http://www.ubertheme.com/
 * Version: 1.0
 * Description: 
 * Author: Uber theme team
 * Author URI: http://www.ubertheme.com/
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
?>
<?php
	$productCollection = $this->getCollection();
	$helper = $this->helper('catalog/output');
	$profileConfigs = null;
	if(Mage::helper('core')->isModuleEnabled('Wavethemes_Jmbasetheme')){
		$profileConfigs = Mage::helper("jmbasetheme")->getProfileContent();
	}

	if ($profileConfigs) :
		$productListImageWidth = $profileConfigs["productlistimagewidth"];
		$productListImageHeight = $profileConfigs["productlistimageheight"];
		$productGridDesLength = $profileConfigs["productgriddeslenght"];
		$productGridImageHeight = $profileConfigs["productgridimageheight"];
		$productGridImageWidth = $profileConfigs["productgridimagewidth"];
		$showLabel = $profileConfigs["showlabel"];
	else :
		$productListImageWidth = 180;
		$productListImageHeight = 180;
		$productGridDesLength = 0;
		$productGridImageHeight = 180;
		$productGridImageWidth = 180;
		$showLabel = 0;
	endif;

	$collectionSize = $productCollection ? $productCollection->count() : 0;
	$thumbWidth = $config['width'];
	$thumbHeight = $config['height'];
	$maxChar = $config['max'];
	
	// Calculator with
	if ($config['perrow']){
		$perrow = $config['perrow'];
		$width = 100/$config['perrow'];
	}
	// Tablet
	$perrowtablet = $config["perrowtablet"];
	$widthtablet = 100/$config["perrowtablet"];
	if ($config["perrowtabletportrait"]){
		$perrowtabletportrait = $config["perrowtabletportrait"];
		$widthtabletportrait = 100/$config["perrowtabletportrait"];
	}
	else {
		$perrowtabletportrait = $perrowtablet;
		$widthtabletportrait = $widthtablet;
	}

	// Mobile
	$perrowmobile = $config["perrowmobile"];
	$widthmobile = 100/$config["perrowmobile"];
	if ($config["perrowmobileportrait"]){
		$perrowmobileportrait = $config["perrowmobileportrait"];
		$widthmobiletportrait = 100/$config["perrowmobileportrait"];
	}
	else {
		$perrowmobileportrait = $perrowmobile;
		$widthmobiletportrait = $widthmobile;
	}
?>
<style type="text/css">
	.jm-product-list ul.products-grid li.item {
			width: <?php echo $width.'%';?>;
		}
	.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
    clear: both;
	}
	@media only screen and (min-width:986px) and (max-width: 1235px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthtablet.'%';?>;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
	    clear: both;
		}
	}
	@media only screen and (min-width:720px) and (max-width: 985px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthtabletportrait.'%';?>;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtabletportrait;?>n+1) {
	    clear: both;
		}
	}
	@media only screen and (max-width:719px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthmobile.'%';?>;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowtabletportrait;?>n+1) {
	    clear: none;
		}
		.jm-product-list ul.products-grid > li:nth-child(<?php echo $perrowmobile;?>n+1) {
	    clear: both;
		}
	}
	@media only screen and (max-width:479px) {
		.jm-product-list ul.products-grid li.item {
			width: <?php echo $widthmobiletportrait.'%';?>;
		}
		<?php if ($perrowmobileportrait == 1):?>
			.jm-product-list ul.products-grid {
				margin: 0;
			}
		<?php endif; ?>
	}
</style>

<?php if (!$collectionSize): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<div class="jm-product-list <?php echo $config['mode']; ?> clearfix">
		<div class="page-title category-title clearfix">
			<h1>
				<?php echo Mage::getSingleton('core/session')->getData('jm_product_title') ? Mage::getSingleton('core/session')->getData('jm_product_title') : $config['title']; ?>
			</h1>
		</div>
		<div class="category-products">
			<!--Tool bar-->
			<?php echo $this->getToolbarHtml() ?>
			<!--//Tool bar		-->
			
			<!-- List mode -->
			<?php if ($this->getMode() != 'grid'): ?>
				<?php $iterator = 0; ?>
				<ol class="products-list" id="products-list">
					<?php foreach ($productCollection as $product): ?>
						<li class="item<?php if (++$iterator == sizeof($productCollection)): ?> last<?php endif; ?>">
							<?php // Product Image ?>
							<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>" class="product-image">
								<img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize($thumbWidth, $thumbHeight)->setWatermarkSize('30x10'); ?>"	alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/>
							</a>
							<?php // Product description ?>
							<div class="product-shop">
								<div class="f-fix">
									<?php $productNameStripped = $this->stripTags($product->getName(), null, true); ?>
									<h2 class="product-name">
										<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $helper->productAttribute($product, $product->getName() , 'name'); ?></a>
									</h2>
									<?php echo $this->getReviewsSummaryHtml($product, true, true) ?>
									<?php echo $this->getPriceHtml($product, true) ?>
									<?php if($product->isSaleable()): ?>
										<p>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										</p>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									<?php if($config['max']):?>
										<div class="desc std">
											<?php
												$productDesc = $product->getDescription();
												$productShortDesc = $product->getShortDescription();
												echo substr(nl2br(strlen($productDesc) > 10 ? $productDesc : $productShortDesc), 0, $config['max']) . '...';
											?>
											<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $productNameStripped ?>" class="link-learn">
												<?php echo $this->__('Learn More') ?>
											</a>
										</div>
									<?php endif;?>

									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li>
												<a href="<?php echo $this->helper('wishlist')->getAddUrl($product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
											</li>
										<?php endif; ?>
										<?php if ($compareUrl = $this->getAddToCompareUrl($product)): ?>
											<li>
												<span class="separator">|</span> 
												<a href="<?php echo $compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
											</li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
				</ol>
				<script type="text/javascript">decorateList('products-list', 'none-recursive');</script>

			<?php else: ?> 
				<!-- Grid mode -->
				<ul class="products-grid">
					<?php
					$i = 0; $j=0;
					foreach ($productCollection as $product):
						$rowCount = ceil($collectionSize / $columnCount);
						if ($i % $columnCount == 0) : $j++; endif;
						if ($i++ % $columnCount == 0):
							$product = Mage::getModel('catalog/product')->load($product->getId());
							$attribute = $product->getResource()->getAttribute('label');
							if (is_object($attribute)) {
								$attDefaultValue = $attribute->getDefaultValue();
								$attributeValue = Mage::getModel('catalog/product')->load($product->getId())->getlabel();
								$attributeValueName = Mage::getModel('catalog/product')->load($product->getId())->getAttributeText('label');
								if (strlen($attributeValue) && ($attDefaultValue !== $attributeValue)) {
									$labelType = $attributeValueName;
								} else {
									$labelType = "";
								}
							}
						?>

						<?php endif ?>
						<li class="item <?php if ($j == $rowCount) : echo "item-row-last"; endif; ?> <?php if (($i - 1) % $columnCount == 0): ?> first<?php elseif ($i % $columnCount == 0): ?> last<?php endif; ?> p-item">
							<div class="inner">
								<?php // Product image ?>
								<p class="product-image">
									<a href="<?php echo $product->getProductUrl() ?>"
									   title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"><img
											src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize($thumbWidth, $thumbHeight)->setWatermarkSize('30x10'); ?>"
											alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/></a>
									<?php if (isset($labelType)): ?>
										<span class="<?php echo $labelType; ?>-label label"><?php echo $labelType; ?></span>
									<?php endif; ?>
								</p>
								<?php // Product Description ?>
								<div class="product-information">
									<h2 class="product-name">
										<a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $helper->productAttribute($product, $product->getName(), 'name') ?></a>
									</h2>
									<?php echo $this->getReviewsSummaryHtml($product, true, true) ?>
									<?php echo $this->getPriceHtml($product, true, '_jmproduct_' . uniqid()); ?>

									<?php
									if ($maxChar) :
										$productDesc = $product->getDescription();
										$productShortDesc = $product->getShortDescription();
										?>
										<p class="pdescription"><?php echo substr(nl2br(strlen($productDesc) > 10 ? $productDesc : $productShortDesc), 0, $maxChar) . '...'; ?></p>
									<?php endif; ?>
									<?php if ($product->isSaleable()): ?>
										<button class="button btn-cart"
												onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')">
											<span><?php echo $this->helper("catalog")->__('Add to Cart'); ?></span>
										</button>
									<?php else: ?>
										<div
											class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock'); ?></div>
									<?php endif; ?>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($product); ?>"
												   class="link-wishlist">
													<?php echo $this->__('Wishlist'); ?>
												</a></li>
										<?php endif; ?>
										<?php if ($compareUrl = $this->getAddToCompareUrl($product)): ?>
											<li>
												<a href="<?php echo $compareUrl ?>"
												   class="link-compare"><?php echo $this->__('Compare'); ?></a></li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
						</li>
					<?php endforeach ?>
				</ul>
			<?php endif; ?>

			<div class="toolbar-bottom">
				<?php echo $this->getToolbarHtml() ?>
			</div>
		</div>
	</div>
<?php endif; ?>
